apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-website-db-0
  namespace: student-project
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: db-pv
