apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.100.104
  share: /var/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
