apiVersion: v1
kind: Service
metadata:
  name: website 
  namespace: student-project
  labels:
    app: website
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30002 
  selector:
    name: website
