apiVersion: v1
kind: Service
metadata:
  name: postgres 
  namespace: student-project
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: website-db
  selector:
    app: postgres
